### ISSUE TITLE
Reserved IP

### ISSUE THREAD

**Issue by mezen** [mattlongman/Hassio-Access-Point#19]
Hi,

is it possible to always assign a reserved ip adress to specific devices to prevent ip switching over time?

**Comment by AndyOne77** [comment]
support. A very useful function.

**Comment by esotericnonsense** [comment]
#23

**Comment by esotericnonsense** [comment]
I have put together a pull request for this functionality in #23.

**Comment by Dejv311** [comment]
HI!
This addon does not allow you to do this, but after a few hours of reverse-engineering the whole thing I found a way to work around it. Basically I am using code injection to add a line specifying mac->ip reservation. The IP needs to be in the "range" specified above. There can be multiple lines of "dhcp-host" added specifying multiple reservations. The hashtag at the last line is very important - do not remove it!!  Hope this helps :)

My config:
```
ssid: MyWifi
wpa_passphrase: password123
channel: '6'
address: 192.168.99.1
netmask: 255.255.255.0
broadcast: 192.168.99.255
interface: wlan0
hide_ssid: '1'
dhcp: '1'
dhcp_start_addr: 192.168.99.10
dhcp_end_addr: |-
  192.168.99.200,12h
  dhcp-host=12:34:56:78:90:AB,192.168.99.123
   #
allow_mac_addresses: []
deny_mac_addresses: []
debug: 0
hostapd_config_override: []
client_internet_access: '1'
client_dns_override: []
```

**Comment by Dejv311** [comment]
Hi, thank you. It looks like the update solved the issue! The dhcp_end_addr shenanigans are a left over from past versions, where dnsmasq_config_override did not exist. I will leave it like that since it looks cool :D. Anyways thanks again for your time!

**Comment by mattlongman** [comment]
Thanks @Dejv311. To confirm, you're talking about the issue on https://github.com/mattlongman/Hassio-Access-Point/issues/30?

**Comment by Dejv311** [comment]
Sorry, wrong thread, yes it works now :)

**Comment by mattlongman** [comment]
Adding `dhcp-host=12:34:56:78:90:AB,192.168.99.123` to `dnsmasq_config_override` is now the best way to do this.
