### ISSUE TITLE
hostapd.conf request

### ISSUE THREAD

**Issue by mineroloco55** [mattlongman/Hassio-Access-Point#2]
Would it be possible to include some of the hostapd options :?
hw_mode = g
wpa = 2
wpa_key_mgmt = WPA-PSK
wpa_pairwise = TKIP
rsn_pairwise = CCMP
ieee80211n = 1
ht_capab = LDPC (these last two are interesting to leave it in "n")

in this way we reduce the width of the channel and gain some stability in the wifi

**Comment by mattlongman** [comment]
Maybe a dict in the addon config to override hostapd options... I'll look into it.

**Comment by mattlongman** [comment]
The base config is [here](https://github.com/mattlongman/Hassio-Access-Point/blob/master/hassio-access-point/hostapd.conf), and then run.sh appends other items based on the config. In short, this is what is already in the config:

```
driver=nl80211
hw_mode=g
ieee80211n=1
wmm_enabled=1
ht_capab=[HT40][SHORT-GI-20][DSSS_CCK-40]
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
logger_stdout=-1
logger_stdout_level=2
```

I'm not that familiar with hostapd, so I'm happy to defer to anyone who can improve performance. If there's something in the default config that you think should be changed, please submit a PR.

Apart from that, I'm adding another addon config option, to allow you to specify/override hostapd config options.

**Comment by mattlongman** [comment]
@mineroloco55 - please update the addon and see if that works for you. Add something like this to your config:
"hostapd_config_override": ["wpa_pairwise=TKIP", "ht_capab=LDPC"]

**Comment by mineroloco55** [comment]
great your override run.
how quickly you responded!

**Comment by mineroloco55** [comment]
ht_capab = LDPC
LDPC not run with the actual driver
