### ISSUE TITLE
HomeAssistant on RPi4 Wifi Question

### ISSUE THREAD

**Issue by iosoft** [mattlongman/Hassio-Access-Point#25]
Hello,

I am using HomeAssistant on Raspberry Pi 4.

Can I use Pi4's 5GHz Network to connect my Home Network and 2.4GHz as Wifi Access Point for some IoT devices?

**Comment by G2G2G2G** [comment]
no, you could use both to connect theoretically.. but there is a hardware limitation in access point mode.

**Comment by mattlongman** [comment]
Hi @iosoft - thanks for the question. As @G2G2G2G said, the answer if technically no (in regards to the two different bands).

However, I'm going to look into this [PR](https://github.com/mattlongman/Hassio-Access-Point/pull/20) which would enable STA+AP mode. This would allow connection of the Pi4 to your home network, and allow other devices to connect to the AP. Worth reading the PR for more information. Stay tuned.

**Comment by CoYoNq** [comment]
Hi
It's possible to set both modes in parallel, but performance is horrible (pi Wireless chipset is very limited). Suggestion on use 2 adapters is, IMHO, the best setup.
