### ISSUE TITLE
How add dev5 on ha

### ISSUE THREAD

**Issue by hellresistor** [mattlongman/Hassio-Access-Point#33]
heya. I want try, but not find how import the dev-5 version into HA   ;|  What is the correct link? thank you

**Comment by mattlongman** [comment]
I've created a release for 0.5a dev branch. https://github.com/mattlongman/Hassio-Access-Point/releases/tag/dev-v0.5a

Virtual interface isn't working (or at least, I haven't confirmed the config to make it work), but isolation is working.

**Comment by hellresistor** [comment]
friend sorry my english I mean when i use that link to add into HA Addon repository will fail "Invalid Add-on repository!"
![errorha](https://user-images.githubusercontent.com/50468493/176364538-a0b06950-3593-4141-86bb-e84aac1e637e.jpg)

**Comment by mattlongman** [comment]
for .zip releases like this, download and extract it, and copy the hassio-access-point folder via SMB to the addons directory. It will then show up as a local addon.

I agree that it would be nice if different branches could be added like you've shown above! Unfortunately, copying over manually is the best way for now.
