### ISSUE TITLE
NO IP without dhcp=1 and no internet

### ISSUE THREAD

**Issue by aladin2000** [mattlongman/Hassio-Access-Point#37]
Hi
i used config using wlp3s0 instead of wlan0 in json file
I have last HAssio release  and I just tried to install the addon ....
  Home Assistant 2022.10.5 
  Supervisor 2022.10.0 
  Interface utilisateur : 20221010.0 - latest 

here is my yaml file
  
`ssid: MYSSID
wpa_passphrase: *****
channel: "1"
address: 192.168.0.1
netmask: 255.255.255.0
broadcast: 192.168.0.255
interface: wlp3s0
hide_ssid: "0"
dhcp: "0"
dhcp_start_addr: 192.168.0.10
dhcp_end_addr: 192.168.0.20
allow_mac_addresses:[]
deny_mac_addresses: []
debug: 0
hostapd_config_override: []
client_internet_access: 1
client_dns_override:
  - 168.168.1.1
  - 8.8.8.8
  - 1.1.1.1
dnsmasq_config_override: []
`

The AP is visible for everybody as I've  finally removed the allowed_macs block data for current tests 

here is the log data

_s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Hass.io Access Point Addon
rfkill: Cannot open RFKILL control device
wlp3s0: interface state UNINITIALIZED->ENABLED
wlp3s0: AP-ENABLED 
wlp3s0: STA  IEEE 802.11: associated
wlp3s0: STA IEE 802.11: deauthenticated due to local deauth request
wlp3s0: STA IEEE 802.11: disassociated_

and another try ....
wlp3s0: AP-STA-CONNECTED xx:yy:zz:ss:tt:uu
wlp3s0: STA xx:yy:zz:ss:tt:uu RADIUS: starting accounting session 7A9689A2145F5705
wlp3s0: STA xx:yy:zz:ss:tt:uu WPA: pairwise key handshake completed (RSN)
wlp3s0: EAPOL-4WAY-HS-COMPLETED xx:yy:zz:ss:tt:uu
wlp3s0: STA xx:yy:zz:ss:tt:uu IEEE 802.11: disassociated
wlp3s0: AP-STA-DISCONNECTED xx:yy:zz:ss:tt:uu

.... 
Hope that could help to find a fix 

Next try , The following is my investigations  
I added dhcp=1  to find the root cause. 
ip is OK if dhcp=1 is configured  **but no internet access** 

**may be it is problem of dns not forwarding to the router dns** ? 
 
....
Add to hostapd.conf: accept_mac_file=/hostapd.allow
Add to hostapd.conf: interface=wlx4c0fc718df88
DHCP enabled. Setup dnsmasq:
Add to dnsmasq.conf: dhcp-range=192.168.0.10,192.168.0.20,12h
Add to dnsmasq.conf: interface=wlx4c0fc718df88
Add custom DNS: dhcp-option=6,1.1.1.1,8.8.8.8,192.168.1.1
 Starting dnsmasq daemon
 Starting hostapd daemon
rfkill: Cannot open RFKILL control device
wlx4c0fc718df88: interface state UNINITIALIZED->ENABLED
wlx4c0fc718df88: AP-ENABLED 
wlx4c0fc718df88: STA secret IEEE 802.11: authenticated
wlx4c0fc718df88: STA secret IEEE 802.11: associated (aid 1)
wlx4c0fc718df88: AP-STA-CONNECTED secret 
wlx4c0fc718df88: STA secret  RADIUS: starting accounting session secret 
wlx4c0fc718df88: STA secret  WPA: pairwise key handshake completed (RSN)
wlx4c0fc718df88: EAPOL-4WAY-HS-COMPLETED secret

**Comment by mattlongman** [comment]
Hi @aladin2000 

'NO IP without dhcp=1' - if you don't have DHCP enabled, you'll need to manually set an IP

'client_dns_override: 168.168.1.1' - Double check this. Did you try 192.168.1.1 instead?

**Comment by aladin2000** [comment]
> Hi @aladin2000
> 
> 'NO IP without dhcp=1' - if you don't have DHCP enabled, you'll need to manually set an IP
> 
> 'client_dns_override: 168.168.1.1' - Double check this. Did you try 192.168.1.1 instead?

I removed the dns override , the 168.168 was a Typo error  
I added a route back from parent router   : 192.168.99.0 / 255.255.255.0 to 192.168.1.7 ( ip of HASS server ) 
Then the dhcp ip is good from the addon, but I still have a problem to reach Internet from the client:   
Here are the new config file  


ssid: SSID1
wpa_passphrase: secret
channel: 1
address: 192.168.99.1
netmask: 255.255.255.0
broadcast: 192.168.99.255
interface: wlx4c0fc718df88
hide_ssid: "0"
dhcp: 1
dhcp_start_addr: 192.168.99.10
dhcp_end_addr: |
  192.168.99.150,12h
  dhcp-host=sec1  ,192.168.99.133
  dhcp-host=sec2,192.168.99.130
  dhcp-host=sec3,192.168.99.18
allow_mac_addresses:
  - mac sec1
  - mac sec2
  - mac sec3
deny_mac_addresses: []
debug: 0
hostapd_config_override: []
client_internet_access: 1
client_dns_override: []
dnsmasq_config_override: []

**Comment by aladin2000** [comment]
it is fixed now. 
I just put the orerride option for dns that is the ip of tHe homeassistant server ip. INSTEAD of parent routeur from the FAI
 
Internet is OK but still strange things regarding some url not found . probably the dns synchronisation.
