### ISSUE TITLE
Feature Request: Routing client internet traffic via primary wireless connection

### ISSUE THREAD

**Issue by MariusHerget** [mattlongman/Hassio-Access-Point#43]
Hey,

I have read in  #13 ([comment](https://github.com/mattlongman/Hassio-Access-Point/issues/13#issuecomment-894211990)) that the internet traffics is routed through eth. I have a usecase where I want to connect to a WiFi (with a second wireless device) but still provide a hotspot for my local IoT devices (which sometimes need internet access).

Has this feature been added since the comment, and if not: Is it possible to implement this?

Best Marius

**Comment by mattlongman** [comment]
If you had a second (compatible) Wi-Fi card then this would theoretically be possible with some code changes. The pre-release [0.4.5](https://github.com/mattlongman/Hassio-Access-Point/releases/tag/v0.4.5) has the option to specify the 'ethernet' interface which in this case would be the Wi-Fi connection connecting to the main network.

Unfortunately, I don't have the equipment to test this.

**Comment by MariusHerget** [comment]
Thanks! Will check it out :)

**Comment by MariusHerget** [comment]
Just checked it out. Can confirm that this works!

Thank you very much!

```
Test Setup:
- Host Wifi via an Integrated Wifi Card (Intel Wireless-AC 3165)
- Hotspot WiFi via an TP-Link ARCHER T3U PLUS USB WiFi Antenna (rtl88x2bu chipset)
```
