### ISSUE TITLE
Home Assistant OS 11.0 breaks client_internet_access

### ISSUE THREAD

**Issue by rrooggiieerr** [mattlongman/Hassio-Access-Point#55]
From the Home Assistant OS 11.0 change log:

⚠️ Breaking Change: On Arm based boards network names are enumerated based on device tree. This means that the first Ethernet devices will no longer be named eth0 but end0. The network configuration is automatically applied to the new network interface.

**Comment by mattlongman** [comment]
https://github.com/mattlongman/Hassio-Access-Point/pull/56
