### ISSUE TITLE
Cannot Add repository into HA

### ISSUE THREAD

**Issue by hellresistor** [mattlongman/Hassio-Access-Point#7]
Hello!

I am getting same issue has original repository from DavidRamos.

My system:
core-2021.7.1
supervisor-2021.06.8
Raspbian GNU/Linux 10 (buster)
HA Supervisor (Using dedicated script)

Error returned wind webwindow:
`The command '/bin/bash -o pipefail -c apk update && apk add --no-cache bash jq iw hostapd networkmanager net-tools sudo dnsmasq && rm -rf /var/cache/apk/*' returned a non-zero code: 2`
![zzz](https://user-images.githubusercontent.com/50468493/125199507-6852eb80-e25e-11eb-82f0-bb239b2d434c.png)

Supervisor log:
```
21-07-11 14:53:18 INFO (SyncWorker_0) [supervisor.docker.addon] Starting build for 30e576d0/armv7-addon-hassio-access-point:0.3.1
21-07-11 14:53:21 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build 30e576d0/armv7-addon-hassio-access-point:0.3.1: The command '/bin/bash -o pipefail -c apk update && apk add --no-cache bash jq iw hostapd networkmanager net-tools sudo dnsmasq && rm -rf /var/cache/apk/*' returned a non-zero code: 2
21-07-11 14:53:21 ERROR (SyncWorker_0) [supervisor.docker.addon] Build log: 
Step 1/17 : ARG BUILD_FROM
Step 2/17 : FROM $BUILD_FROM
 ---> 564b1f71f9e5
Step 3/17 : MAINTAINER Matt Longman <git@mattlongman.com>
 ---> Using cache
 ---> cba61f51108e
Step 4/17 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> 201f6713278d
Step 5/17 : ENV LANG C.UTF-8
 ---> Using cache
 ---> 31b77a0159f9
Step 6/17 : RUN apk update && apk add --no-cache bash jq iw hostapd networkmanager net-tools sudo dnsmasq && rm -rf /var/cache/apk/*
 ---> Running in cf0367c686fc
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)
WARNING: 
Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: No such file or directory

fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: No such file or directory

2 errors; 39 distinct packages available
Removing intermediate container cf0367c686fc
```

PS: Have that packages installed with apt-get command (networkmanager should be network-manager ?)

**Comment by hellresistor** [comment]
Found this to on supervisor log

```
21-07-11 21:05:30 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Hassio Hostapd Extended
21-07-11 21:05:30 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Hassio Hostapd Extended
21-07-11 21:05:31 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Hassio Hostapd Extended
21-07-11 21:05:31 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Hassio Hostapd Extended
```

**Comment by mattlongman** [comment]
Can you confirm whether you get the same error after rebooting? Seems like it could be a DNS issue when trying to access the alpine CDN. If it's a DNS issue at the CDN's end, it should resolve itself after a period of time.

**Comment by mattlongman** [comment]
Similar issues reported on [this thread](https://github.com/gliderlabs/docker-alpine/issues/334) on the Docker-Alpine repo

**Comment by hellresistor** [comment]
> u confirm whether you get the same error after rebo

Confirm after reboot, keeps.

it supose do that on all Addons or just on yours? why?

**Comment by mattlongman** [comment]
Hi @hellresistor. I've tested this on different units, with different versions, and I can't recreate this error. Have you had any luck since?

Does is work if you try using HAOS instead of Raspbian (if you have a spare SD card to test with)? I'm not sure of the ramifications of using HA supervisor on a different OS. Or even, trying with the latest Raspberry Pi OS instead of Buster?

**Comment by hellresistor** [comment]
This is the software versions.
I am Using Raspbian buster + Homeassistant Superviser script!

![Screenshot_1](https://user-images.githubusercontent.com/50468493/126268902-ba680300-a9f8-4bc0-aeeb-7b6b3d760155.png)

I will try today do a new installation

**Comment by rlust** [comment]
Trying to install on a HASSIO latest, when I enter the URL provided to add add-on, it hangs.

This looks great, just what I need!
Thanks!

**Comment by hellresistor** [comment]
Can Confirm. On HASSIOS Is OK!

But I need this on and raspbian because need configure i2c and set some commands in bash :|

Should be Docker version?

**Comment by mattlongman** [comment]
@hellresistor - thanks for testing this. I'll have a look and see if I can recreate then try to work out what is causing this.

@rlust - are you having this issue on HAOS or raspbian with hassio supervisor on top?

**Comment by mattlongman** [comment]
I'm not very familiar with home assistant supervised on alternative operating systems, but if you need access to more than HAOS gives you, have you considered using [the supported Debian](https://community.home-assistant.io/t/installing-home-assistant-supervised-on-a-raspberry-pi-with-debian-10/247116) route?

**Comment by mattlongman** [comment]
Ok, a few false starts, but flashed Debian 10 and followed the [setup guide](https://community.home-assistant.io/t/installing-home-assistant-supervised-on-a-raspberry-pi-with-debian-10/247116). Once I'm into Home Assistant, I can add the repo `https://github.com/mattlongman/Hassio-Access-Point` without issue, then I can install it too.

```
21-07-20 22:16:43 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/mattlongman/Hassio-Access-Point repository
21-07-20 22:16:45 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 1 new - 0 remove
21-07-20 22:16:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-07-20 22:16:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-07-20 22:16:49 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/30e576d0_hassio-access-point
21-07-20 22:16:49 INFO (SyncWorker_5) [supervisor.docker.addon] Starting build for 30e576d0/aarch64-addon-hassio-access-point:0.3.1
21-07-20 22:17:31 INFO (SyncWorker_5) [supervisor.docker.addon] Build 30e576d0/aarch64-addon-hassio-access-point:0.3.1 done
21-07-20 22:17:31 INFO (MainThread) [supervisor.addons] Add-on '30e576d0_hassio-access-point' successfully installed
```

Configured the add-on and tested it - working as expected (good to know!)

**Comment by hellresistor** [comment]
Well . It is Working! 
Raspbian Will Not. BUT ON Debian Yes!

**Comment by hellresistor** [comment]
friends, I am able install other addons on my 1st system (where i get pronlem with your addon). It is Just with your rep.

You should do some investigation. If you need OS versions... methods ..etc ... to reproduce. you just need the rpi4 (mine 4GB). I am able to help!

**Comment by mattlongman** [comment]
Hi @hellresistor - please provide the OS versions, steps etc. I can't promise I'll be able to look at it soon, but I am intrigued.

That said it'll be more difficult to support this as HA Supervised is unsupported on Raspberry Pi OS.

It could still be the issue with the alpine docker repo. Have you confirmed other repos which use alpine docker work correctly on RasPi OS?

**Comment by hellresistor** [comment]
Hya @mattlongman sorry de late answer. today got sd damaged and need start a new configuration on the next days. i will note all steps. and if you want i can provide an sdcard clone image. Well i think will use debian 11 arm64 as OS. or you prefer keep on debian 10 ? best regards

**Comment by hellresistor** [comment]
@mattlongman  here my steps,

Download image here Debian 11 Rpi4 -> https://raspi.debian.net/tested-images/

In Local keyboard:
```
apt update && apt upgrade -y
apt install sudo -y
adduser YOUR_USERNAME
usermod -aG sudo YOUR_USERNAME
ip addr show eth0
reboot
```

In SSH login Session with YOUR_USERNAME:
```
sudo -i

apt update && sudo apt upgrade -y && sudo apt autoremove -y
apt-get install -y jq curl avahi-daemon apparmor-utils udisks2 libglib2.0-bin network-manager dbus wget systemd-journal-remote

systemctl disable ModemManager && systemctl stop ModemManager

curl -fsSL get.docker.com | sh

## Checkk last version
wget https://github.com/home-assistant/os-agent/releases/download/1.4.1/os-agent_1.4.1_linux_aarch64.deb
dpkg -i os-agent_1.4.1_linux_aarch64.deb

wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
dpkg -i homeassistant-supervised.deb

```
