### ISSUE TITLE
Versions don't match. Restarting NetworkManager is advised.

### ISSUE THREAD

**Issue by iqubik** [mattlongman/Hassio-Access-Point#71]
Warning: nmcli (1.44.4) and NetworkManager (1.42.4) versions don't match. Restarting NetworkManager is advised.

**Comment by ROBOT0-VT** [comment]
See issue #60 

This happens in base HASS too, and doesn't really do anything except leave an annoying error message, so not really our concern.

Thanks for raising it though!
